### ISSUE TITLE
Subscript out of bounds error when running library(MetaboShiny)

### ISSUE THREAD

**Issue by BartHee** [UMCUGenetics/MetaboShiny#42]
running start.metshi(inBrowser = T) opens and closes with the following errors:
start.metshi(inBrowser = T)
[1] "Orca isn't working, please check your installation. If on Mac, please try starting Rstudio from the command line with the command 'open -a Rstudio'"

Listening on http://0.0.0.0:8080
Warning: Error in [[: subscript out of bounds
  46: MetaboShiny::getOptions
  45: <observer> [C:\Program Files\R\R-3.6.0\library\MetaboShiny/server.R#184]
   2: shiny::runApp
   1: start.metshi
Warning: Error in [[: subscript out of bounds
  75: MetaboShiny::getOptions
  74: MetaboShiny::setOption
  73: observeEventHandler [C:\Program Files\R\R-3.6.0\library\MetaboShiny/server.R#951]
   2: shiny::runApp
   1: start.metshi
Warning: Error in [[: subscript out of bounds
  75: MetaboShiny::getOptions
  74: MetaboShiny::setOption
  73: observeEventHandler [C:\Program Files\R\R-3.6.0\library\MetaboShiny/server.R#962]
   2: shiny::runApp
   1: start.metshi
Warning: Error in [[: subscript out of bounds
  75: MetaboShiny::getOptions
  74: MetaboShiny::setOption
  73: observeEventHandler [reactive/aesthetics.R#36]
   2: shiny::runApp
   1: start.metshi
Warning in match(x, table, nomatch = 0L) :
  closing unused connection 8 (~/MetaboShiny/saves/admin/options.txt)
Warning in match(x, table, nomatch = 0L) :
  closing unused connection 7 (~/MetaboShiny/saves/admin/options.txt)
Warning in match(x, table, nomatch = 0L) :
  closing unused connection 6 (~/MetaboShiny/saves/admin/options.txt)
Warning: The 'plotly_click' event tied a source ID of 'A' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_click')` to the plot (`p`) that you wish to obtain event data from.
[1] "Closing metaboShiny ~ヾ(＾∇＾)"

**Comment by BartHee** [comment]
Running on Docker, this error persists. Perhaps it is something in the saves/admin/options.txt file (however, checking ls does not give odd rows). 
This is the options file content:

db_dir = ~/MetaboShiny/databases
work_dir = ~/MetaboShiny/saves/admin
proj_name = MY_METSHI
ppm = 2
packages_installed = Y
font1 = Pacifico
font2 = Pacifico
font3 = Open Sans
font4 = Open Sans
col1 = #000000
col2 = #DBDBDB
col3 = #FFFFFF
col4 = #FFFFFF
size1 = 40
size2 = 20
size3 = 15
size4 = 11
taskbar_image = metshi_logo.png
gtheme = classic
gcols = #1C1400&#FFE552&#D49C1A&#EBC173&#8A00ED&#00E0C2&#95C200&#FF6BE4&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF&#FFFFFF
gspec = RdBu
mode = complete
cores = 1
apikey =

**Comment by joannawolthuis** [comment]
Thanks for putting it on Github Bart! Makes it a bit easier for me to keep a mental overview :D 
I will be rolling out a version today that should have this issue fixed. It was due to some new options being added that are not in the older options files - I will be merging with the DEV branch soon, if you want you can already switch to there:
```
devtools::install_github("UMCUGenetics/MetaboShiny", ref="dev")
```
to see if you still run into issues. I will be merging with Master at the end of the day too :)

**Comment by joannawolthuis** [comment]
Oh and also, if you want to export figures, orca is a bit necessary, it is easier to install through conda : O Once installed, it can be used(at least in my case) either through running metshi from the command line or opening rstudio through:

```
open -a rstudio
```
in the command line.

**Comment by BartHee** [comment]
RStudio:
Thanks, the fix worked. I had to remove the previous folder tree ~/MetaboShiny/{databases,saves/admin} in order to have it work. _The localhost 8080 now opens the app!_ **So RStudio is covered**.

Docker:
Pulling the new docker image results in an updated image with a few new downloads. However, running the commands results in the out of bounds error again, so perhaps the docker image is not updated with the @dev yet?
